spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        datasource:
        url: mysql://b59e741daeef4e90e4c626us-cdbr-east-02.cleardb.com/heroku_2598849bc0bb9e7?reconnect=true
        driver-class-name: com.mysql.jdbc.Driver
        username: enbrdlgyqqaftu
        password: 32bf0c43b20cf747bd3e80c7da477d70d7d5af25152d04c451658cf6a110122b
